name: Weather Bot

on:
  schedule:
    # 毎日6時に実行
    - cron: "0 21 * * *"
  workflow_dispatch: # 手動実行用のトリガー
    inputs:
      customMessage:
        description: "送信するカスタムメッセージ" # 必須ではない入力項目
        required: false
        default: "定期天気予報"

jobs:
  send-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run weather bot
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: node index.js
